FROM alpine

#Installing curl
RUN apk add --no-cache curl

#Installing git
RUN apk add --no-cache git

#Installing grpe
RUN apk add --no-cache grep=3.3-r0

#Installing bash
RUN apk update
RUN apk upgrade
RUN apk add bash